import { UseFormFactoryProps } from '@/hooks/factories';
import { InquiryData } from './Inquiry.d';

export const inquiryFormConfig: UseFormFactoryProps<InquiryData> = {
  sections: [
    {
      name: 'status',
      label: 'Status',
      gridItemProps: { xs: 12 },
    },
    {
      name: 'employee',
      label: 'Employee Information',
    },
    {
      name: 'position',
      label: 'Position Information',
    },
    {
      name: 'comment',
      label: 'Comments',
      gridItemProps: { xs: 12 },
    },
  ],
  fields: [
    {
      name: 'id',
      label: 'id',
      type: 'text',
      section: 'status',
      hidden: true,
      sortOrder: 1,
    },
    {
      name: 'state',
      label: 'Current State',
      type: 'status',
      section: 'status',
      sortOrder: 2,
    },
    {
      name: 'candidate_first_name',
      label: 'First Name',
      type: 'text',
      required: true,
      section: 'employee',
      sortOrder: 1,
    },
    {
      name: 'candidate_last_name',
      label: 'Last Name',
      type: 'text',
      required: true,
      section: 'employee',
      sortOrder: 2,
    },
    {
      name: 'current_position_number',
      label: 'Current Position Number',
      type: 'text',
      section: 'employee',
      sortOrder: 6,
    },
    {
      name: 'current_position_title',
      label: 'Current Position Title',
      type: 'text',
      section: 'employee',
      sortOrder: 5,
    },
    {
      name: 'current_ministry_id',
      label: 'Current Ministry',
      type: 'select',
      selectionOptions: {
        endPoint: 'ministry',
        labelFieldName: 'ministry_name',
        valueFieldName: 'id',
      },
      section: 'employee',
      sortOrder: 3,
    },
    {
      name: 'current_annual_salary',
      label: 'Current Annual Salary',
      type: 'currency',
      section: 'employee',
      sortOrder: 7,
    },
    {
      name: 'current_mccf_classification',
      label: 'Current Classification',
      type: 'text',
      section: 'employee',
      sortOrder: 4,
    },
    {
      name: 'experience_level_id',
      label: 'Experience Level',
      type: 'select',
      selectionOptions: {
        endPoint: 'experience',
        labelFieldName: 'experience_level',
        valueFieldName: 'id',
        sortFieldName: 'experience_level',
      },
      section: 'position',
      sortOrder: 5,
    },
    {
      name: 'new_position_number',
      label: 'New Position Number',
      type: 'text',
      required: true,
      section: 'position',
      sortOrder: 2,
    },
    {
      name: 'new_position_title',
      label: 'New Position Title',
      type: 'text',
      required: true,
      section: 'position',
      sortOrder: 1,
    },
    {
      name: 'new_mccf_classification_id',
      label: 'New Classification',
      type: 'select',
      required: true,
      section: 'position',
      sortOrder: 3,
      selectionOptions: {
        endPoint: 'classification',
        labelFieldName: 'classification',
        valueFieldName: 'id',
        sortFieldName: 'minimum_salary',
      },
    },
    {
      name: 'appointment_id',
      label: 'Appointment Type',
      type: 'select',
      selectionOptions: {
        endPoint: 'appointment',
        labelFieldName: 'type',
        valueFieldName: 'id',
      },
      section: 'position',
      sortOrder: 6,
    },
    {
      name: 'process_id',
      label: 'Process Type',
      type: 'select',
      selectionOptions: {
        endPoint: 'process',
        labelFieldName: 'type',
        valueFieldName: 'id',
      },
      section: 'position',
      sortOrder: 7,
    },
    {
      name: 'salary_estimate',
      label: 'Salary Estimate',
      type: 'currency',
      section: 'position',
      sortOrder: 4,
    },
    {
      name: 'hm_comment',
      label: 'Hiring Manager Comments',
      type: 'multiline',
      section: 'comment',
      sortOrder: 1,
    },
    {
      name: 'hm_user',
      label: 'HM GUID',
      type: 'text',
      section: 'status',
      hidden: true,
      sortOrder: 1,
    },
    {
      name: 'shr_comment',
      label: 'Strategic Human Resources Comments',
      type: 'multiline',
      section: 'comment',
      sortOrder: 2,
    },
    {
      name: 'shr_user',
      label: 'SHR GUID',
      type: 'text',
      section: 'status',
      hidden: true,
      sortOrder: 1,
    },
    {
      name: 'adm_comment',
      label: 'Assistant Deputy Minister Comments',
      type: 'multiline',
      section: 'comment',
      sortOrder: 3,
    },
    {
      name: 'adm_user',
      label: 'ADM GUID',
      type: 'text',
      section: 'status',
      hidden: true,
      sortOrder: 1,
    },
  ],
  title: 'Inquiries',
  view: {
    show: true,
  },
  edit: {
    show: true,
  },
  remove: {
    show: true,
    confirmationField: 'new_position_title',
  },
  create: {
    show: true,
    defaultValues: {
      id: 0,
      state: 'draft',
      candidate_first_name: '',
      candidate_last_name: '',
      current_position_number: '',
      current_position_title: '',
      current_ministry_id: null,
      current_annual_salary: 0,
      current_mccf_classification: '',
      experience_level_id: null,
      new_position_number: '',
      new_position_title: '',
      new_mccf_classification_id: null,
      appointment_id: null,
      process_id: null,
      salary_estimate: 0,
      hm_comment: '',
      hm_user_id: null,
      shr_comment: '',
      shr_user_id: null,
      adm_comment: '',
      adm_user_id: null,
    },
  },
};
