/**
 * @summary All seed data for deva dn prod
 * @author Dallascrichmond
 */
export const salaryRanges = [
    { id: 1, definition: 'Band 1', minimum_salary: 63400, maximum_salary: 90399.95 },
    { id: 2, definition: 'Band 2', minimum_salary: 74300, maximum_salary: 105000.04 },
    { id: 3, definition: 'Band 3', minimum_salary: 86200, maximum_salary: 122100.01 },
    { id: 4, definition: 'Band 4', minimum_salary: 102900, maximum_salary: 136700.11 },
    { id: 5, definition: 'Band 5', minimum_salary: 119600, maximum_salary: 152599.97 },
    { id: 6, definition: 'Band 6', minimum_salary: 137700, maximum_salary: 168500.09 },
];

export const statuses = [
    { id: 1 },
    { id: 2 },
    { id: 3 },
    { id: 4 },
    { id: 5 },
    { id: 6 },
];

// TODO: Add all minitries
export const ministries = [
    { id: '', ministry_name: ''},
    { id: 'CITZ', ministry_name: 'Citizen Services' },
    { id: 'PSA', ministry_name: 'Public Service Agency' },
];

export const experienceLevels = [
    { id: 1, definition: 'No experience' },
    { id: 2, definition: 'Little experience' },
    { id: 3, definition: 'Some experience' },
    { id: 4, definition: 'Lots of experience' },
];

export const appointments = [
    { id: 1, definition: 'TA'},
    { id: 2, definition: 'REG' },
];

export const processes = [
    { id: 1, definition: 'Competitive Process' },
    { id: 2, definition: 'Internal Process' }
];

export const users = [
    {
        guid: 'SQJHDNJASBC12388271267GS718G',
        username: 'DALRICH',
        email: 'dallas.richmond@gov.bc.ca',
        user_first_name: 'Dallas',
        user_last_name: 'Richmond',
        roles: [
            'hm',
        ],
    },
    {
        guid: 'KJBCKJBDFWE928371761JBJH71',
        username: 'CARLTHOM',
        email: 'carl.thomas@gov.bc.ca',
        user_first_name: 'Carl',
        user_last_name: 'Thomas',
        roles: [
            'shr',
        ],
    },
    {
        guid: 'AJSIUC0002948433KDOJEWNDFHD',
        username: 'CARLTHOM',
        email: 'carl.thomas@gov.bc.ca',
        user_first_name: 'Carl',
        user_last_name: 'Thomas',
        roles: [
            'adm',
        ],
    },
]

export const inquiries = [
    {
        status_id: 1,
        inquiry_completion_date: null,
        candidate_first_name: 'Dallas',
        candidate_last_name: 'Richmond',
        current_position_number: null,
        current_position_title: null,
        current_ministry_id: null,
        current_annual_salary: null,
        current_mccf_classification_id: null,
        experience_level_id: 1,
        new_position_number: '2938475',
        new_position_title: 'Scrum Master',
        new_mccf_classification_id: 3,
        appointment_type_id: 1,
        process_type_id: 1,
        salary_estimate: null,
        hm_comment: null,
        shr_comment: null,
        adm_comment: null,
        hm_user_id: 'SQJHDNJASBC12388271267GS718G',
        shr_user_id: 'KJBCKJBDFWE928371761JBJH71',
        adm_user_id: 'AJSIUC0002948433KDOJEWNDFHD',
    },
    {
        status_id: 6,
        inquiry_completion_date: null,
        candidate_first_name: 'Tyler',
        candidate_last_name: 'Smith',
        current_position_number: '293847',
        current_position_title: 'Manager',
        current_ministry_id: 'PSA',
        current_annual_salary: 80000,
        current_mccf_classification_id: 'IS30',
        experience_level_id: 3,
        new_position_number: '2938475',
        new_position_title: 'Team Lead',
        new_mccf_classification_id: 2,
        appointment_type_id: 1,
        process_type_id: 1,
        salary_estimate: 102000,
        hm_comment: 'Here is the successful candidate',
        shr_comment: 'Here is the salary estimate. Reach out if you have any questions',
        adm_comment: null,
        hm_user_id: 'SQJHDNJASBC12388271267GS718G',
        shr_user_id: null,
        adm_user_id: null,
    },
    {
        status_id: 2,
        inquiry_completion_date: null,
        candidate_first_name: 'Cindy',
        candidate_last_name: 'Charles',
        current_position_number: '293847',
        current_position_title: 'Full Stack Developer',
        current_ministry_id: 'CITZ',
        current_annual_salary: 80000,
        current_mccf_classification_id: null,
        experience_level_id: 3,
        new_position_number: '2938475',
        new_position_title: 'Scrum Master',
        new_mccf_classification_id: 3,
        appointment_type_id: 1,
        process_type_id: 1,
        salary_estimate: 102000,
        hm_comment: 'Here is the successful candidate',
        shr_comment: 'Here is the salary estimate. Reach out if you have any questions',
        adm_comment: null,
        hm_user_id: 'SQJHDNJASBC12388271267GS718G',
        shr_user_id: 'KJBCKJBDFWE928371761JBJH71',
        adm_user_id: null,
    },
];

export const salaryData = [
    {
        "organization": "Citizen Services",
        "program": "OCIO Enterprise Services",
        "program_division": "Information Management Branch",
        "position_number": 124008,
        "title": "Intermediate Developer, Java",
        "job_code": 508010,
        "classification": "Band 3",
        "appointment": "R",
        "schedule": "F",
        "supervisor_position_number": 129079,
        "employee_id": 174833,
        "employee_job_code": 508011,
        "employee_classification": "Band 3",
        "step": 1,
        "position_job_code_max_annual_rate": 136700,
        "employee_job_code_max_annual_rate": 136700,
        "abbr": 105000,
        "ama": 349
    },
    {
        "organization": "Citizen Services",
        "program": "OCIO Enterprise Services",
        "program_division": "Information Management Branch",
        "position_number": 867530,
        "title": "Systems Architect",
        "job_code": 707070,
        "classification": "Band 3",
        "appointment": "R",
        "schedule": "F",
        "supervisor_position_number": 987654,
        "employee_id": 246813,
        "employee_job_code": 707071,
        "employee_classification": "Band 3",
        "step": 999,
        "position_job_code_max_annual_rate": 555555,
        "employee_job_code_max_annual_rate": 555555,
        "abbr": 123456,
        "ama": 789
    },
    {
        "organization": "Citizen Services",
        "program": "OCIO Enterprise Services",
        "program_division": "Information Management Branch",
        "position_number": 543210,
        "title": "Machine Learning Engineer",
        "job_code": 111111,
        "classification": "Band 3",
        "appointment": "R",
        "schedule": "F",
        "supervisor_position_number": 987123,
        "employee_id": 987654,
        "employee_job_code": 111112,
        "employee_classification": "Band 3",
        "step": 222,
        "position_job_code_max_annual_rate": 444444,
        "employee_job_code_max_annual_rate": 444444,
        "abbr": 777777,
        "ama": 888
    },
    {
        "organization": "Citizen Services",
        "program": "OCIO Enterprise Services",
        "program_division": "Information Management Branch",
        "position_number": 987654,
        "title": "Cybersecurity Analyst",
        "job_code": 999999,
        "classification": "Band 3",
        "appointment": "R",
        "schedule": "F",
        "supervisor_position_number": 111111,
        "employee_id": 234567,
        "employee_job_code": 999900,
        "employee_classification": "Band 3",
        "step": 333,
        "position_job_code_max_annual_rate": 222222,
        "employee_job_code_max_annual_rate": 222222,
        "abbr": 444444,
        "ama": 555
    },
    {
        "organization": "Citizen Services",
        "program": "OCIO Enterprise Services",
        "program_division": "Information Management Branch",
        "position_number": 135790,
        "title": "DevOps Engineer",
        "job_code": 123123,
        "classification": "Band 3",
        "appointment": "R",
        "schedule": "F",
        "supervisor_position_number": 567890,
        "employee_id": 345678,
        "employee_job_code": 123124,
        "employee_classification": "Band 3",
        "step": 444,
        "position_job_code_max_annual_rate": 111111,
        "employee_job_code_max_annual_rate": 111111,
        "abbr": 666666,
        "ama": 111
    },
    {
        "organization": "Citizen Services",
        "program": "OCIO Enterprise Services",
        "program_division": "Information Management Branch",
        "position_number": 246813,
        "title": "Data Scientist",
        "job_code": 555555,
        "classification": "Band 3",
        "appointment": "R",
        "schedule": "F",
        "supervisor_position_number": 432109,
        "employee_id": 876543,
        "employee_job_code": 555556,
        "employee_classification": "Band 3",
        "step": 555,
        "position_job_code_max_annual_rate": 333333,
        "employee_job_code_max_annual_rate": 333333,
        "abbr": 999999,
        "ama": 222
    }
];
