FROM node:20-bullseye-slim

WORKDIR /app

ENV NODE_ENV=development

COPY package*.json ./

RUN npm install

COPY . .

# Force clean cache to avoid issues with .npm permissions
RUN npm cache clean --force

RUN npx prisma generate

#For debugging: create and write the contents of start.sh in the container
RUN rm start.sh
RUN echo "#!/bin/bash" >> start.sh && \
    echo "# push the schema to the database and sync the client" >> start.sh && \
    echo "npx prisma db push --schema='/usr/src/app/prisma/schema.prisma' --skip-generate " >> start.sh && \
    echo "" >> start.sh && \
    echo "# Start the application" >> start.sh && \
    echo "npm run start:dev" >> start.sh

# Set execute permissions for the start.sh script.
RUN chmod +x ./start.sh

EXPOSE 3000

CMD ["./start.sh"]
