FROM node:20-bullseye-slim

WORKDIR /app

ENV NODE_ENV=development

COPY . .

RUN npm install

# Force clean cache to avoid issues with .npm permissions
RUN npm cache clean --force

EXPOSE 3000

CMD ["npm", "run", "dev"]

