FROM node:20.5-bullseye-slim as build

WORKDIR /app

RUN apt-get update && apt-get install -y curl

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:1.24-alpine as prod

COPY nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=build /app/build .

RUN chmod g+rwx /var/cache/nginx /var/run /var/log/nginx

EXPOSE 8080

ENTRYPOINT ["nginx", "-g", "daemon off;"]
